scanner:
    diff_only: True  # Only show errors caused by the patch
    linter: flake8

message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: "Hello @{name}, thank you for submitting the Pull Request!"
        footer: "To test for issues locally, `pip install flake8` and then run `flake8 fury`."
    updated:  # Messages when new commits are added to the PR
        header: "Hello @{name}, Thank you for updating!"
        footer: "To test for issues locally, `pip install flake8` and then run `flake8 fury`."
    no_errors: "Cheers! There are no style issues detected in this Pull Request. :beers: "

pycodestyle:
    max-line-length: 88  # Default is 79 in PEP8
    # ignore:  # Errors and warnings to ignore
    #    - W391
    #    - E203
    # exclude:
    #     - doc/examples
    #     - dipy/info.py
    #     - doc/conf.py
flake8:  # Valid if scanner.linter is flake8
    max-line-length: 88  # Default is 79 in PEP8
    ignore: []
    exclude: []
    count: False
    show-source: False
    statistics: False
    hang-closing: False
    filename: []
    select: []

only_mention_files_with_errors: True  # If False, a separate status comment for each file is made.
descending_issues_order: False # If True, PEP8 issues in message will be displayed in descending order of line numbers in the file
