target-version = "py310"
line-length = 88
force-exclude = true
extend-exclude = [
  "__pycache__",
  "build",
  "_version.py",
  "docs/experimental/**",
]

[lint]
select = [
  "F",
  "E",
  "C",
  "W",
  "B",
  "I",
]
ignore = [
  "B905",
  "C901",
  "E203"
]

[lint.extend-per-file-ignores]
"docs/examples/**" = ["I001"]
"docs/source/conf.py" = ["E402"]

[lint.flake8-quotes]
inline-quotes = "double"

[lint.isort]
case-sensitive = true
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["fury"]
no-sections = false
order-by-type = true
relative-imports-order = "closest-to-furthest"
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[format]
quote-style = "double"
