"""Actor module for FURY."""

__all__ = [
    "actor_from_primitive",
    "line",
    "sphere",
    "ellipsoid",
    "cylinder",
    "cone",
    "arrow",
    "axes",
    "box",
    "tetrahedron",
    "icosahedron",
    "triangularprism",
    "pentagonalprism",
    "octagonalprism",
    "rhombicuboctahedron",
    "frustum",
    "superquadric",
    "streamtube",
    "disk",
    "image",
    "marker",
    "point",
    "ring",
    "square",
    "star",
    "text",
    "triangle",
    "billboard",
    "sph_glyph",
    "vector_field",
    "vector_field_slicer",
    "surface",
    "SphGlyph",
    "data_slicer",
    "VectorField",
    "volume_slicer",
    "peaks_slicer",
    "streamlines",
    "line_projection",
    "create_mesh",
    "create_line",
    "create_point",
    "create_text",
    "create_image",
    "Mesh",
    "Line",
    "Points",
    "Text",
    "Image",
    "Group",
    "Volume",
    "Actor",
    "set_group_opacity",
    "set_opacity",
    "set_group_visibility",
    "apply_affine_to_group",
    "apply_affine_to_actor",
    "get_slices",
    "show_slices",
    "contour_from_volume",
    "contour_from_roi",
    "contour_from_label",
    "read_buffer",
]

from .billboard import billboard, billboard_sphere
from .bio import contour_from_label, contour_from_roi, peaks_slicer, volume_slicer
from .core import (
    Actor,
    Group,
    Image,
    Line,
    Mesh,
    Points,
    Text,
    Volume,
    actor_from_primitive,
    arrow,
    axes,
    create_image,
    create_line,
    create_mesh,
    create_point,
    create_text,
    line,
)
from .curved import cone, cylinder, ellipsoid, sphere, streamlines, streamtube
from .planar import (
    disk,
    image,
    line_projection,
    marker,
    point,
    ring,
    square,
    star,
    text,
    triangle,
)
from .polyhedron import (
    box,
    frustum,
    icosahedron,
    octagonalprism,
    pentagonalprism,
    rhombicuboctahedron,
    superquadric,
    tetrahedron,
    triangularprism,
)
from .slicer import (
    SphGlyph,
    VectorField,
    data_slicer,
    sph_glyph,
    vector_field,
    vector_field_slicer,
)
from .topology import contour_from_volume, surface
from .utils import (
    apply_affine_to_actor,
    apply_affine_to_group,
    get_slices,
    read_buffer,
    set_group_opacity,
    set_group_visibility,
    set_opacity,
    show_slices,
)
