# This is a basic workflow to help debugging FURY

name: FuryDebug

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        type: boolean
      operating_system:
        description: "Select on which operating system you want to debug"
        required: false
        type: string
        default: ubuntu-latest
      python_version:
        description: "Select the python version during the debugging"
        required: false
        type: string
        default: '3.8'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ]
        python-version: [3.8, ]
        platform: [x64]
        install_type: [pip, ] 
        depends: [DEFAULT_DEPS, OPTIONAL_DEPS]
        pip-flags: ['']
        option-flags: ['']
        experimental: [false]
    env:
      TRAVIS_PYTHON_VERSION: ${{ matrix.python-version }} # Keep backward compatibilty with Travis
      TRAVIS_REPO_SLUG: ${{ github.repository }}          # Keep backward compatibilty with Travis
      TRAVIS_BRANCH: ${{ github.head_ref }}               # Keep backward compatibilty with Travis
      TRAVIS_PULL_REQUEST: ${{ github.event.number }}     # Keep backward compatibilty with Travis
      TRAVIS_BUILD_DIR: ${{ github.workspace }}           # Keep backward compatibilty with Travis
      DISPLAY: :99.0
      GH_REF: github.com/fury-gl/fury-website.git
      ENV_DIR: ${{ github.workspace }}/envs
      INSTALL_TYPE: ${{ matrix.install_type }}
      PRE_PIP_FLAGS: '--pre --extra-index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple'
      EXTRA_PIP_FLAGS: ${{ matrix.pip-flags }}
      OPTION_FLAGS: ${{ matrix.option-flags }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: |
          ~/.cache/pip
          ~/.ccache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Setup Environment variables
      run: |
        if [ "macos-latest" == "${{ matrix.os }}" ]; then echo "TRAVIS_OS_NAME=osx" >> $GITHUB_ENV; else echo "TRAVIS_OS_NAME="${{ matrix.os }}"" >> $GITHUB_ENV; fi
        if [ "ubuntu-latest" == "${{ matrix.os }}" ]; then echo "MPLBACKEND=TKAgg" >> $GITHUB_ENV; fi
        if [ "schedule" == "${{ github.event_name }}" ]; then echo "TRAVIS_EVENT_TYPE=cron" >> $GITHUB_ENV; else echo "TRAVIS_EVENT_TYPE="${{ github.event_name }}"" >> $GITHUB_ENV; fi
        if [ "OPTIONAL_DEPS" == "${{ matrix.depends }}" ]; then echo "OPTIONAL_DEPS=1" >> $GITHUB_ENV; else echo "OPTIONAL_DEPS=0" >> $GITHUB_ENV; fi
        python3 -c "import os; print(os.environ['OPTION_FLAGS'])"
        echo "COVERAGE=$(python3 -c "import os; print(int('COVERAGE' in os.environ['OPTION_FLAGS'].split(' ')))")" >> $GITHUB_ENV;
        echo "BUILD_DOCS=$(python3 -c "import os; print(int('BUILD_DOCS' in os.environ['OPTION_FLAGS'].split(' ')))")" >> $GITHUB_ENV;
        echo "DEPLOY_DOCS=$(python3 -c "import os; print(int('DEPLOY_DOCS' in os.environ['OPTION_FLAGS'].split(' ')))")" >> $GITHUB_ENV;
        echo "USE_PRE=$(python3 -c "import os; print(int('USE_PRE' in os.environ['OPTION_FLAGS'].split(' ')))")" >> $GITHUB_ENV;
    - name: Print some Environment variables
      run: |
        echo "TRAVIS_OS_NAME: ${TRAVIS_OS_NAME}"
        echo "TRAVIS_EVENT_TYPE: ${TRAVIS_EVENT_TYPE}"
        echo "ENV_DIR: ${ENV_DIR}"
        echo "OPTIONAL_DEPS: ${OPTIONAL_DEPS}"
        echo "COVERAGE: ${COVERAGE}"
        echo "BUILD_DOCS: ${BUILD_DOCS}"
        echo "DEPLOY_DOCS: ${DEPLOY_DOCS}"
        echo "USE_PRE: ${USE_PRE}"
    - name: Start Xvfb
      if: startsWith(matrix.os,'ubuntu')
      run: |
        if [ "ubuntu-18.04" == "${{ matrix.os }}" ]; then
          sudo apt-get install -y libgl1-mesa-dev xvfb;
        else
          sudo apt-get install -y libgl1-mesa-glx libglx-mesa0 libglx-dev libglx0 xvfb;
        fi
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1  &
        sleep 3
    - name: Install dependencies
      run: |
        bash ci/travis/install.sh
    - name: Install FURY and Test it!
      run: |
        bash ci/travis/script.sh
    - name: Deploy docs
      if: success() && github.ref == 'refs/heads/master'
      run: |
        bash ci/travis/deploy_docs.sh
